import Item1 from "../../assets/item-1.png?react"
import Item2 from "../../assets/item-2.png?react"
import Item3 from "../../assets/item-3.png?react"
import Item4 from "../../assets/item-4.png?react"
import Item5 from "../../assets/item-5.png?react"
import Item6 from "../../assets/item-6.png?react"
import Item7 from "../../assets/item-7.png?react"
import Item8 from "../../assets/item-8.png?react"
import Item9 from "../../assets/item-9.png?react"
import Item10 from "../../assets/item-10.png?react"
import Item11 from "../../assets/item-11.png?react"
import Item12 from "../../assets/item-12.png?react"
import Item13 from "../../assets/item-13.png?react"
import Item14 from "../../assets/item-14.png?react"
import Item15 from "../../assets/item-15.png?react"
import Item16 from "../../assets/item-16.png?react"

